dtc_grid:
    reflection:
        # allow any entity to be shown via the /dtc_grid route
        # allowed_entities: ~, '*', or an array of entity names [ 'App:Product', 'App:Category', ... ]
        #  ~ - no entities allowed for reflection
        #  * - all entities allowed for reflection
        #  [ 'App:Product', 'App:Category' ] - only App:Product and App:Category allowed
        allowed_entities: ~
    purl: '//cdnjs.cloudflare.com/ajax/libs/purl/2.3.1/purl.js'
    jquery:
        url: '//code.jquery.com/jquery-3.4.1.min.js'
        integrity: 'sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo='
        crossorigin: anonymous
    datatables:
        css:
            - '//cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css'
        js:
            - '//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js'
            - '//cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js'
        options:
            # datatables options
            processing: true,
            searchDelay: 350,
            table_attr:
                class: "display table table-striped table-bordered small-font"
            serverSide: true
            language:
                # # Example language change:
                # url: "https://cdn.datatables.net/plug-ins/1.10.19/i18n/German.json"
                # # See more here: https://datatables.net/plug-ins/i18n/
                #
                # NOTE: If using an alternate language than english, feel free to remove or comment-out the below line:
                lengthMenu: _MENU_ records per page
    jq_grid:
        css:
            - https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/font/octicons.css
            # - 'path_or_url_to/prettify.css'
            # - 'path_or_url_to/ui.jqgrid-bootstrap4.css'
        js:
            # - 'path_or_url_to/grid.locale-en.js'
            # # If using other languages include a locale like below:
            # - 'path_or_url_to/grid.locale-de.js'
            # - 'path_or_url_to/jquery.jqGrid.js'
        options:
            # # Example language change:
            # regional: de
            datatype: json
            jsonReader:
                root: rows
                total: total
                records: records
                page: page
                repeatitems: false
            url: ~
            cell: ""
            width: 840
            height: 400
            loadui: disable
            altRows: true
            viewrecords: true
            multiselect: true
            styleUI: 'Bootstrap4'
            iconSet: 'Octicons'
            prmNames:
                page: page
                rows: limit
                sort: sort_column
                order: sort_order
                nd: ~
            ajaxGridOptions:
                cache: false,
                ifModified: false,
            pager: grid-pager
    table:
        options:
            table_attr:
                class: display table table-striped table-bordered small-font
    theme:
        css:
            - '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
            -
                url: '//stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'
                integrity: 'sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh'
                crossorigin: anonymous
        js:
            -
                url: 'https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js'
                integrity: 'sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo'
                crossorigin: anonymous
            -
                url: '//stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js'
                integrity: 'sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6'
                crossorigin: anonymous
    page_div_style: 'margin: 10px'
